# Config options
markdown: redcarpet
highlighter: true

# don't need any of these in our build directory
exclude: [
  README.md,
  package.json,
  node_modules,
  npm-debug.log,
  assets/stylus,
  Gemfile,
  Gemfile.lock,
  deploy.sh
]

title: Famous Framework

collections:
  pages:
    output: true

defaults:

navigation:
  -
    name: Overview
    children:
      -
        name: 'Hello Framework'
        path: 'hello-framework'
        next: 'Getting Started'
        nextPath: getting-started
        children:
      -
        name: 'Getting Started'
        path: getting-started
        previous: 'Hello Framework'
        previousPath: 'hello-framework'
        next: 'Core Concepts'
        nextPath: core-concepts
        children:
      -
        name: 'Core Concepts'
        path: core-concepts
        previous: 'Getting Started'
        previousPath: getting-started
        next: Behaviors
        nextPath: behaviors
        children:
  -
    name: Essentials
    children:
      -
        name: Behaviors
        path: behaviors
        previous: 'Core Concepts'
        previousPath: core-concepts
        next: Events
        nextPath: events
        children:
      -
        name: Events
        path: events
        previous: Behaviors
        previousPath: behaviors
        next: States
        nextPath: states
        children:
      -
        name: States
        path: states
        previous: Events
        previousPath: events
        next: Tree
        nextPath: 'tree'
        children:
      -
        name: Tree
        path: 'tree'
        previous: States
        previousPath: states
        next: Layout
        nextPath: 'layout'
        children:
      -
        name: Layout
        path: layout
        previous: Tree
        previousPath: 'tree'
        next: Control flow
        nextPath: 'control-flow'
        children:
      -
        name: Control flow
        path: control-flow
        previous: Layout
        previousPath: layout
        next: 'Deploy / publish'
        nextPath: deployment
        children:
  -
    name: Intermediate
    children:
      -
        name: 'Deploy / publish'
        path: deployment
        previous: Control flow
        previousPath: control-flow
        next: External Files
        nextPath: external-files
        children: ~
      -
        name: Includes
        path: includes
        previous: 'Deploy / publish'
        previousPath: deployment
        next: Imports
        nextPath: imports
        children: ~
      -
        name: Imports
        path: imports
        previous: Includes
        previousPath: includes
        next: Static Assets
        nextPath: static-assets
      -
        name: Static Assets
        path: static-assets
        previous: Imports
        previousPath: imports
        next: Timelines
        nextPath: timelines
      -
        name: Timelines
        path: timelines
        previous: Static Assets
        previousPath: static-assets
        next: API Docs
        nextPath: $dispatcher
  -
    name: API Docs
    children:
      -
        name: $dispatcher
        path: $dispatcher
        previous: Timelines
        previousPath: timelines
        next: '$event'
        nextPath: $event
        children: ~
      -
        name: $event
        path: $event
        previous: '$dispatcher'
        previousPath: $dispatcher
        next: $index
        nextPath: $index
        children: ~
      -
        name: "$index"
        path: $index
        previous: $event
        previousPath: $event
        next: $payload
        nextPath: $payload
      -
        name: $payload
        path: $payload
        previous: $index
        previousPath: $index
        next: $repeatPayload
        nextPath: $repeatPayload
      -
        name: $repeatPayload
        path: $repeatPayload
        previous: $payload
        previousPath: $payload
        next: $route
        nextPath: $route
      -
        name: $route
        path: $route
        previous: $repeatPayload
        previousPath: $repeatPayload
        next: $state
        nextPath: $state
      -
        name: $state
        path: $state
        previous: $route
        previousPath: $route
        next: $timelines
        nextPath: $timelines
      -
        name: $timelines
        path: $timelines
        previous: $state
        previousPath: $state
        next: Syntactic sugar
        nextPath: sugar
        children: ~
      -
        name: Syntactic sugar
        path: sugar
        previous: $timelines
        previousPath: $timelines
  -
    name: 'Troubleshooting'
    children:
      -
        name: FAQ
        path: faq
  -
      lessons: Lessons

lessons:
  -
    title: Apple TV
    navigation:
      -
        name: Welcome
        path: index
      -
        name: Getting Started
        path: getting-started
      -
        name: Structuring an App
        path: structuring-an-app
      -
        name: Behaviors
        path: behaviors
      -
        name: Adding State
        path: adding-state
      -
        name: Setting Images
        path: setting-images
      -
        name: Positioning Images
        path: positioning-images
      -
        name: Creating Animations
        path: animations
      -
        name: Rotations
        path: rotations
      -
        name: Finish
        path: finish